### ISSUE TITLE
not sure why column with numbers (sometimes decimal, sometimes not) is varchar?

### ISSUE THREAD

**Issue by mgavery** [uwescience/sqlshare#2]
screenshot here:

https://www.evernote.com/shard/s74/sh/9d605fbc-a3d7-45d5-8af4-e4d8103c2789/e831cb988f6d387fa9be0cf215df2b50

also tried to cast a float or cast as decimal and got an error

**Comment by kubu4** [comment]
Ignore this comment.  See Dan's comments below.  I'm leaving this here for posterity, although any mods can feel free to remove it to clean up the conversation.

Mac, 

In that query, you're selecting all columns (SELECT \* FROM part of your query).  I suspect that's why it fails.  Some columns are strings (i.e. alphabet characters) while other columns are numbers.  Thus, I think that's why you get that "varchar" error.

So, write your SELECT statement to specify which columns you want it to work on.

**Comment by dhalperi** [comment]
I think Mac's right, and the error is because it thinks that the `ratio` field is a `varchar`. Can you point at the actual dataset so I can investigate?

**Comment by dhalperi** [comment]
P.S. Mac, it looks like you tried all the right things -- casting as decimal or float -- so I think there's something deeper going on with the dataset. Such as, maybe one row way down has a letter in it.

**Comment by mgavery** [comment]
yes, you are correct. There are NA's in that column.  Thanks!!

**Comment by dhalperi** [comment]
Gotcha; so you've probably already figured this out, but replace it with something like this?

``` sql
CASE WHEN ratio = 'NA' THEN 0 ELSE CAST(ratio TO FLOAT) END
```
