### ISSUE TITLE
Error Uploading file: Records in data uploaded for FILE_ID...

### ISSUE THREAD

**Issue by sr320** [uwescience/sqlshare#37]
I get the following error attempting to upload a 250k txt file in web interface. 
The sliding bar (bluish) completes, there is a pause and the following comes up.
(This happens with multiple files)

---

Error!

Error Uploading file: Records in data uploaded for FILE_ID = A6567AA53F were not saved.

**Comment by sr320** [comment]
- note that I can upload the file using the python client just fine

**Comment by dhalperi** [comment]
@sr320: We will need a link to the file itself in order to look into this issue.

@billhowe , @shrjain -- any time to debug this?

**Comment by shrjain** [comment]
Its because you are out of quota. 

"quota": 60 GB
"usage": 61.61131286621038 GB

I can fix it by increasing the quota, but I see that there is < 4GB space left in sqlshare db. So you might need to clean up some datasets if possible. 

(I know that the error message is less than useless, will have to fix it. Also, it should have failed via the python client too, which means there is another issue I need to fix.)

**Comment by sr320** [comment]
Thanks @shrjain 
Can I get a list of my "big" files- ie sorted by size?

I think @billhowe might be looking into getting us a local version (or other options) to take some pressure off the main server?

**Comment by shrjain** [comment]
This might help. 

![image](https://cloud.githubusercontent.com/assets/5483063/3501249/a95991e8-0614-11e4-8cc9-03b3a89c304e.png)
