### ISSUE TITLE
Download as Tab-Delimited File

### ISSUE THREAD

**Issue by sr320** [uwescience/sqlshare#4]
Is there a way to download directly as tab-delimited file as opposed to csv?

**Comment by dhalperi** [comment]
I don't think there is a way to do this from the UI, @billhowe? The `python` code can, I think, by passing an optional argument.

**Comment by billhowe** [comment]
Correct -- the UI is behind in a variety of ways, and this is one.  Do we have an online example of the Python/REST call to download tab-delimited?

**Comment by dhalperi** [comment]
Yes, there is a pointer on the [REST API page](http://escience.washington.edu/what-we-do/sqlshare-rest-api). You simply need to pass the `format=tsv` query parameter to the `/v1/db/file?sql={sql}&format={format}` API call.

I don't believe that the Python tools support this right now.

**Comment by dhalperi** [comment]
.. but I'm working on it now.

**Comment by dhalperi** [comment]
Hi Steven,

I've updated the Python tools so that there is a way to control the format of a downloaded file.

I've also moved the Python tools to GitHub. So you can delete (or move out of the way :) your existing copy of the `pythonclient` and then follow the (very similar) instructions [here](https://github.com/uwescience/sqlshare-pythonclient#a-python-client-for-the-sqlshare-rest-api) to download the new ones.

The example of how to download a file in tab-separated value format is [here](https://github.com/uwescience/sqlshare-pythonclient#download-a-dataset)

Note that you'll need `git`, which is built into OS X by default.

Dan

**Comment by sr320** [comment]
Thanks
Ran into error with fetchdata and posted on pythonclient page
https://github.com/uwescience/sqlshare-pythonclient/issues/1

**Comment by dhalperi** [comment]
Thanks Steven. As mentioned over there, this issue has been handled and so I'll close it.
