### ISSUE TITLE
cast column to numeric?

### ISSUE THREAD

**Issue by mgavery** [uwescience/sqlshare#5]
I am doing something wrong with syntax.  I am trying to get a subset of data where the column named 'score' is >=0.25, but the score column is 'varchar' and so I need to convert it to a number (in a previous step I removed any rows that had text in this column)

SELECT \* FROM [mgavery@washington.edu].[CGbigill5x_asgff]
  where score((cast(score as numeric) >=0.25​

currently I am getting this error: Problem running query: Incorrect syntax near '0.25'.

**Comment by kubu4** [comment]
Looks like you need to close your parentheses.  You have three open parentheses "((cast(" ,but only 1 close parentheses "numeric)".

**Comment by dhalperi** [comment]
Hi Mac.
1. As you copied this query, there seems to be a mismatch in the parentheses in your query. But that's not the main problem.
2. The line should be `CAST(score AS NUMERIC) >= 0.25`. In other words, you don't need to put `score` outside the `(CAST ...)` -- the "value" of the `CAST(...)` is the value of `score` interpreted as a number.

[Note that the uppercase/lowercase doesn't matter, but I like to capitalize SQL keywords so I can keep them visually separated].

**Comment by mgavery** [comment]
Thanks both! I am still getting an error..

SELECT \* FROM [mgavery@washington.edu].[CGbigill5x_asgff]
  CAST(score AS NUMERIC) >= 0.25​

Problem running query: "score" is not a recognized table hints option. If it is intended as a parameter to a table-valued function or to the CHANGETABLE function, ensure that your database compatibility mode is set to 90.

**Comment by dhalperi** [comment]
I think you dropped the `WHERE` this time.

I realize that this is probably my fault---I shouldn't have said "the line should be" but rather something like "the WHERE clause should be." Sorry!

**Comment by mgavery** [comment]
ugh, sorry :)

SELECT \* FROM [mgavery@washington.edu].[CGbigill5x_asgff]
 WHERE CAST(score AS NUMERIC) >= 0.25​

Problem running query: Error converting data type varchar to numeric.

**Comment by dhalperi** [comment]
Could this be the same 'NA' problem? There are likely letters somewhere in that table.

**Comment by mgavery** [comment]
I deleted rows with NA's already.  Is there another way to look for any kind of text in that column? 

can I use the '_' or something?

**Comment by dhalperi** [comment]
I see you made the dataset public; I'm looking into this. let you know more when I figure it out. :)

**Comment by dhalperi** [comment]
Hi Mac,

I think I tracked down the issue. It's crazy, and I can't quite explain it, so I have an email out to Bill asking for more details. Basically, I think that SQLServer is ignoring the `ratio not like 'NA'` part of your view, maybe because it's a very slow function to run.

But I think we can fix it, simply by editing [CGbigill5x_asgff](https://sqlshare.escience.washington.edu/sqlshare#s=query/mgavery%40washington.edu/CGbigill5x_asgff)
1. Instead of `ratio NOT LIKE 'NA'`, use `ratio <> 'NA'`; it's much faster so SQLServer might not ignore that part of your code.
2. Put the `CAST(ratio AS FLOAT) AS score` directly in the definition of `CGbigill5x_asgff`. Essentially, convert value types as close to the raw data as possible so you don't have to replicate these `CAST` statements all over the place.

Finally, `NUMERIC` is the wrong type. By default, it allows 0 digits right of the decimal point. So

```
CAST('0.4' AS NUMERIC) < 0.25
```

is true! I don't think this is what you want.

**Comment by dhalperi** [comment]
I should restate this. SQL Server is not "ignoring" that part of your code. Instead, it looks like SQLServer appears to be evaluating it AFTER the `CAST` to float, which will obviously fail in the `NA` case. This is dumb, and again, Bill may come back with something more appropriate and clever to fix.

**Comment by mgavery** [comment]
Editing CGbigill5x_asgff using the suggested steps 1 and 2 did indeed fix my problem!  Thanks so much!

**Comment by billhowe** [comment]
More background:

The view definitions have changed, so I can't directly reproduce, but what I suspect is happening is this:

The condition score <> 'NA' can be pushed down into the index scan, but ratio NOT LIKE 'NA' condition cannot, since LIKE applies an arbitrary regex.

So this means that score <> 'NA' gets applied, and the bad records never see the CAST.

But without that condition, both the CAST and the ratio NOT LIKE 'NA' are applied at the same time in the same operator, so the error gets thrown.

In general, the database is free to apply these in any order it wishes, which can be a problem for these data cleaning scenarios.  One option is to make the CAST expression robust using CASE.  

There's no good/preferred way to force the optimizer to evaluate a subquery in a specific order.  This problem comes up with multiple WITH statements sometimes.  A terrible hack is to use TOP N, where N is some value known to be larger than the result set.

**Comment by dhalperi** [comment]
Thanks, Bill. Will keep in mind for future.
