### ISSUE TITLE
"Error saving query" message when editing/updating dataset to contain fewer columns

### ISSUE THREAD

**Issue by kubu4** [uwescience/sqlshare#6]
I have a table with five columns.  I'm trying to rename, and retain, two of the five columns.  However, when I Edit Dataset, enter in my statement, Run Query (which runs successfully), and then click the Update Dataset button, I get "Error saving query". 

Here's the statement, if it's helpful:

SELECT [samwhite@washington.edu].[NWSblastnGBnt_no_rRNA.txt].Column2 AS GI, [samwhite@washington.edu].[NWSblastnGBnt_no_rRNA.txt].Column5 AS Description 
  FROM [samwhite@washington.edu].[NWSblastnGBnt_no_rRNA.txt]

Is there a way to perform this without creating a new dataset?

**Comment by dhalperi** [comment]
Hi, can you please make the dataset public or share it with dhalperi@washington.edu?

**Comment by kubu4** [comment]
It is public now.

**Comment by dhalperi** [comment]
Just to be clear---what's the name of the dataset that you're editing? Is it in fact `NWSblastnGBnt_no_rRNA.txt`?

**Comment by kubu4** [comment]
Yes.

**Comment by dhalperi** [comment]
Then what I think is the problem is a confusion between `derive` and `edit` dataset. Notice that if you edit `NWSblastnGBnt_no_rRNA.txt` the default query is

```
SELECT * FROM [samwhite@washington.edu].[table_NWSblastnGBnt_no_rRNA.txt]
```

You lost the `table_`, which indicates that it should use the raw data, when you wrote the new query. Add it back and it would work fine. Otherwise you'd have a self-referencing dataset and would lose the connection to the raw data.

**Comment by dhalperi** [comment]
(Note that since I'm not logged in as `samwhite@washington.edu`, I can't actually see what the `Edit dataset` query is, that is an educated guess. If it's not quite right, you can find the real answer by hitting `Edit dataset` again.)

**Comment by kubu4** [comment]
Ah!  Thanks!
