### ISSUE TITLE
Using SQLShare for course

### ISSUE THREAD

**Issue by sr320** [uwescience/sqlshare#71]
I would like to use SQLShare for a one week course October 19-24- about 20 students. I am not sure where things are with the transition to new server but would this be ok? If so what server (url) should I use?

thanks

**Comment by katimcisse** [comment]
Hi Stephen, 

Apologies for the delayed reply. 

We hope to have the new beta SQLShare service up by then at http://sqlshare.uw.edu. Since it’s a beta there is risk that this environment will not be completely stable.

The current production SQLShare service will be available: https://sqlshare.escience.washington.edu 

Hope that helps,
Bill

**Comment by sr320** [comment]
Thanks - so it sounds like, to play it safe I will use the escience server.
