### ISSUE TITLE
Download of table hangs for extended period

### ISSUE THREAD

**Issue by sr320** [uwescience/sqlshare#74]
In trying to download the table
https://sqlshare.escience.washington.edu/sqlshare/#s=query/ojuarez%40cicese.edu.mx/Ram-GO-Prot

I get no response, spinning browser tab, bottom status bar indicating "Waiting for sqlshare.....

This goes on for hour +

Any advice of how to obtain this file locally?

thanks

**Comment by billhowe** [comment]
Hi Steven,

You might try the python interface.

Long-running queries can cause timeouts when downloading over the web.

Let us know if you need the incantation.

**Comment by sr320** [comment]
Thanks Bill-
Python interface no good either - runs for 1+ hour, no error, no data downloaded.

Suppose I will resort to doing three joins separately and see if that remedies it...

**Comment by billhowe** [comment]
On Tuesday, February 9, 2016, Steven Roberts notifications@github.com
wrote:

> Thanks Bill-
> Python interface no good either - runs for 1+ hour, no error, no data
> downloaded.
> 
> Suppose I will resort to doing three joins separately and see if that
> remedies it...

The query appeared to finish in a reasonable time for  me, so It may be
something about delivering the results back.

I'm wondering about the size of the final result.

 Shrainik: can you open up SQL Server, create a table with the appropriate
schema, then run this query to using "select into"?

We can see how long it takes, and assuming it succeeds, we can just expose
this table for download and see if that works.  If it doesn't, then the
size alone may be causing trouble.

**Comment by shrjain** [comment]
Starting to look at this. Sorry for the delay.

**Comment by shrjain** [comment]
https://sqlshare.escience.washington.edu/sqlshare/#s=query/shrainik%40gmail.com/matrialized_ram_GO_prot

This link should allow downloading. 

I think the root cause is the dataset [dhalperi@washington.edu].[SPID_GOnumber.txt]. 
This dataset is referenced by [sr320@washington.edu].[SPID and GO Numbers] .

The dataset [dhalperi@washington.edu].[SPID_GOnumber.txt] is a HUGE and is calculated every time the query is run. When a query takes a long time, sometimes it fails midway (eg: via a broken connection) and needs to be restarted. 

I see that a lot of dataset reference [dhalperi@washington.edu].[SPID_GOnumber.txt] or  [sr320@washington.edu].[SPID and GO Numbers] . A permanent solution would be to materialize 
[dhalperi@washington.edu].[SPID_GOnumber.txt] and create an index on top of it.

**Comment by billhowe** [comment]
Thanks!!!!

Can we materialize [dhalperi@washington.edu].[SPID_GOnumber.txt], and
change the names so that most queries use the materialized version instead?

**Comment by shrjain** [comment]
Already on it. 
The only way to materialize views in SQLServer is to create a clustered index on the view. 
And even when this is done, any query referencing the view needs to give the `noexpand` hint to make sure that optimizer doesn't expand the view. (not 100% sure about this)

I am trying a simpler method by creating a table myself and using INSERT INTO new_table (select \* from [dhalperi@washington.edu].[SPID_GOnumber.txt])
But this is taking hours to finish. (possibly because of contention on the dataset, as I see that this dataset is always being accessed by some or the other query)

**Comment by billhowe** [comment]
You are awesome as usual.

I'd be surprised if it was related to contention, unless this table is
frequently being updated. And in that case, the materialization will be a
problem anyway.

Another idea is to see why this big query is slow and see if an index or
two could speed it up.  But it may just be too damn big.

**Comment by sr320** [comment]
Thanks for looking into this.
You guys obviously know more about this than me, but I just wanted to add, this is core join query (same tables) we have run for years.. 
There might be something else going on as we are having problems downloading across the board.. trying multi step query work arounds.

In fact I would love to be able to get `[m.delrio03@gmail.com].[tablerv02_goslim]` as it is needed for an upcoming presentation.

thanks again

**Comment by shrjain** [comment]
Ouch. I think that might be because of the 'helpful measures' I am taking. I am trying to create an index on that big dataset we were talking about earlier and that it is hogging SQLAzure.
I will try to download [m.delrio03@gmail.com].[tablerv02_goslim] directly from server and send it to you (depending on how long the query takes to execute.)

**Comment by shrjain** [comment]
Update: So after materialization, index creation and a database tier upgrade, the query in the dataset https://sqlshare.escience.washington.edu/sqlshare/#s=query/ojuarez%40cicese.edu.mx/Ram-GO-Prot finishes in 15seconds, instead of 10.5 mins. 

But the dataset [m.delrio03@gmail.com].[tablerv02_goslim] seems too big even now, is there an actual query on this dataset (which might have fewer results and download faster)? or do you want to download the entire dataset?

**Comment by sr320** [comment]
Thanks!

the query I would like on `[m.delrio03@gmail.com].[tablerv02_goslim]`

is 

```
SELECT * FROM [m.delrio03@gmail.com].[tablerv02]go
left join [sr320@washington.edu].[GO_to_GOslim]slim 
on go.GOID=slim.GO_id where aspect like 'P'
```

This should reduce from 700k records to 300k records

**Comment by sr320** [comment]
Ok that query just worked for me via the web interface!

Took a couple of minutes but seemed to be just fine.

**Comment by shrjain** [comment]
Oh perfect! are you able to download it though?

**Comment by sr320** [comment]
I was able to download the file, thanks so much!

**Comment by shrjain** [comment]
Awesome!

**Comment by billhowe** [comment]
Thanks Shrainik!!!

"Automatic lazy indexing in response to workload"
